### ISSUE TITLE
feature: HTTPS support

### ISSUE THREAD

**Issue by roycewilliams** [codeforanchorage/pfd-names#8]
The site is currently served as HTTP by default, without redirect. Manually switching to HTTPS throws a security error because of cert name mismatch (the cert is a GitHub cert).

Once that's cleared up, HTTP can then redirect to HTTPS.

**Comment by Arsh25** [comment]
GitHub pages now supports HTTPS and can enabled via the repos' [settings tab](https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https).

**Comment by roycewilliams** [comment]
Y'all are quick!

(And sorry for the semi-duplicate!)

**Comment by NigelKibodeaux** [comment]
Done!

**Comment by roycewilliams** [comment]
NIce - thanks!
